apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
resources:
  - secret-mysql.yaml
  - pvc-mysql.yaml
  - deployment-mysql.yaml
  - service-mysql.yaml
  - pvc-wordpress.yaml
  - deployment-wordpress.yaml
  - service-wordpress.yaml
